apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: kube-logging
data:
  key: QVFBeUdLTmkvQlExS3hBQXlqVGRBaXNMY2hUMy9YbW9XQ3YyeUE9PQ==
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: es-rbd
provisioner: ceph.com/rbd
parameters:
  monitors: 10.10.36.211:6789,10.10.36.212:6789,10.10.36.213:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-logging
  pool: elastic
  userId: admin
  userSecretName: ceph-secret
  fsType: xfs
  imageFormat: "2"
  imageFeatures: "layering"
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: es-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  volumeMode: Filesystem
#  resources:
#    requests:
#      storage: 10Gi
#  storageClassName: es-rbd
